# Generated by Django 2.2.3 on 2019-07-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_api', '0002_auto_20190711_1351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providernamespace',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='providernamespace',
            name='namespace',
        ),
        migrations.RemoveField(
            model_name='providernamespace',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='ProviderNamespace',
        ),
    ]
