# Generated by Django 2.2.3 on 2019-07-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_api', '0003_auto_20190711_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
